### ISSUE TITLE
лаб 5

### ISSUE THREAD

**Issue by lasbio** [DevaMar1a/bd-lab#4]
3 - нет ФИО 
4 - нет названия объекта
5 - не верно
7 - не верно
8 - не верно
9 - не верно
10-18 - не сделано

**Comment by lasbio** [comment]
3 - не верно
5 - ошибка
7 - не верно
8,9 - не точно, не учтена аренда нескольких слотов времени.
10 - название объекта.
11-18 - не выполнены

**Comment by DevaMar1a** [comment]
3,5,7,8,9,10 - исправлены
11-18-выполнены

**Comment by lasbio** [comment]
5 - запишите с крипт без использования функции Date(...)
11 - можно ли обойтись без ROUND?
13 - используйте встроенную функцию row_number()
15 - зачем использована функция COALESCE, нельзя ли обойтись без ROUND?
17 - почему нельзя  использовать NTILE в  derived table?
18 - не используется критерий "за 15 дней"

**Comment by DevaMar1a** [comment]
Задания 5,11,13,15,17 - изменены

**Comment by lasbio** [comment]
11,15 - ?
18 - не верно

**Comment by vzlabiom** [comment]
18 - не верно
